# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_remove_paste_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
